### ISSUE TITLE
Creacion del backend/api

### ISSUE THREAD

**Issue by MiguelPerezMartinez** [MiguelPerezMartinez/apollofy-music-project#26]
Requerimientos:
- Tener el proyecto en github.

Objetivos:
- [x] Estructura del backend.
- [x] Inicialización del servidor.
- [x] Configuración del proyecto (.env, config.js)

Finalización:
- Servidor inicializado.

**Comment by jonathancede** [comment]
Tarea terminada con pull request a develop mergeada.
Pendiente de demo.

**Comment by jonathancede** [comment]
Hay que eliminar el archivo .env del repositorio de github

**Comment by jonathancede** [comment]
Tarea terminada.
