### ISSUE TITLE
Crear base de react/frontend

### ISSUE THREAD

**Issue by MiguelPerezMartinez** [MiguelPerezMartinez/apollofy-music-project#27]
Requerimientos:
- Proyecto en Github.

Objetivos:
- [x] Crear estructura React básica.
- [x] Enrutar las diferentes views:
  - Sign in/Sign up view
  - Home page view (solo basico para enlazar)
  - Profile view
- [x] Estructura del Redux.
- [x] Planteamiento general de la página.

Finalización:
- React inicializado con las diferentes rutas en funcionamiento.

**Comment by jonathancede** [comment]
Pendiente de aceptar la PR.
