### ISSUE TITLE
Cierre de sesion de usuario

### ISSUE THREAD

**Issue by MiguelPerezMartinez** [MiguelPerezMartinez/apollofy-music-project#4]
User History:
- El usuario podrá cerrar la sesión clicando en el botón de cierre de sesión

Requerimientos:
- Conexión del servidor a la BD con una colección de usuarios creada.
- Entorno de Firebase preparado.

Objetivos:
- [x] Gestionar el cierre de sesión en el servidor. Deprecated -> Not necessary.
- [x] Implementar lógica de cierre de sesión en React.

Finalización:
- El usuario clicará en el botón de cierre de sesión y la sesión se debe cerrar.

**Comment by jonathancede** [comment]
Pull request de esta tarea junto con la issue #13 y #5.
