### ISSUE TITLE
Registro de usuario

### ISSUE THREAD

**Issue by MiguelPerezMartinez** [MiguelPerezMartinez/apollofy-music-project#5]
User History:
- El usuario podrá registrarse en el sistema suministrando los datos: Nombre, Apellido, E-mail, Username y Password.

Requerimientos:
- Conexión del servidor a la BD con una colección de usuarios creada.
- Entorno de Firebase preparado.

Objetivos:
- [x] Métodos para registrar un usuario nuevo en el servidor.
- [x] Método de cierre de sesión en Firebase.
- [x] Gestionar lógica de creación de un usuario nuevo en React.
- [x] Implementar formulario de registro.

Finalización:
- El usuario ingresa los datos del formulario de registro y este es añadido a la base de datos (Mongo y Firebase).

**Comment by jonathancede** [comment]
Solucionar el problema del export /api.

**Comment by jonathancede** [comment]
Añadir campos al formulario:
- First name.
- Last name.
