### ISSUE TITLE
Me gusta a una canción dentro del diálogo de información de canción

### ISSUE THREAD

**Issue by jonathancede** [MiguelPerezMartinez/apollofy-music-project#72]
User History:
- El usuario podrá dar “me gusta” a una canción mediante el diálogo de información de canción.

Requerimientos:
- Componente canción implementado.

Objetivos:
- [ ] Implementar estructura del diálogo.
- [ ] Añadir botón me gusta dentro del diálogo.

Finalización:
- Al abrir el diálogo de información, se verá el botón me gusta y se podrá clicar en él.

**Comment by MiguelPerezMartinez** [comment]
Eliminada ya que hemos puesto el icono del fav a los propios elementos track, trackBlock y playbar
